feat(textarea): aplica estilo definido pelo DS
totvs/po-theme-totvs pull request #176
Opened 2022-09-08 21:56 UTC by brunoromeiro

Aplica estilo definido pelo AnimaliaDS

Fixes DTHFUI-6442

2022-09-15 20:16 UTC, rafaellmarques approved these changes

2022-09-15 20:17 UTC, jcorrea97 approved these changes

2022-09-25 17:28 UTC, alinelariguet commented on src/po-theme-custom.css
> +  --color-error: var(--color-feedback-negative-base);
deve apontar para as variáveis legacy. Ex: a variável --color-secondary deve ser utilizada no lugar da variável --color-action-default.

2022-09-25 17:28 UTC, alinelariguet requested changes
verificar comentário anterior.

2022-09-25 21:47 UTC, alinelariguet approved these changes

2022-09-25 22:40 UTC, jcorrea97 approved these changes

2022-09-25 22:41 UTC, merged